repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: name-tests-test
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    - id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
    - id: pyupgrade
      args: [--py3-plus]
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=88, --ignore=E203, --ignore=E231, --ignore=W503]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      additional_dependencies: [numpy==1.21.1]  # update together with version in lock file https://github.com/pre-commit/mirrors-mypy/issues/11
      args: [--strict]
