repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: name-tests-test
    - id: flake8
      args: [--max-line-length=88, --ignore=E203, --ignore=E231, --ignore=W503]
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.2
    hooks:
    - id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.9.0
    hooks:
    - id: pyupgrade
      args: [--py3-plus]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.650
    hooks:
    - id: mypy
      args: [--ignore-missing-imports, --strict]
