name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
